### ISSUE TITLE
Imagen grande en Intro no se escala

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#1]
En una location, si pongo una imagen grande se escala muy bien al tamaño de la pantalla "locBiblioteca.pic =", pero en la intro, si uso "ctrl.ponImg(" y pongo una imagen muy grande, se escapa de la pantalla por la derecha.

**Comment by Baltasarq** [comment]
Mmm... seguro que se puede arreglar, pero de todas formas piensa que al menos la primera vez la imagen va a "venir" por internet... cuanto más pequeña sea, mejor.
