### ISSUE TITLE
Info en la wiki sobre mover al inventario

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#13]
Igual está por ahí, pero me está costando en la wiki encontrar información sobre llevar un objeto al inventario, supongo que es algo como `miObjeto.moveTo(ctrl.personas.getPlayer());`
Imagino que un buen sitio para añadir algo al respecto sería en https://github.com/Baltasarq/fi-js/wiki/Obj#objetos-objetos-contenedores-y-objetos-para-ponerse

**Comment by Baltasarq** [comment]
De acuerdo. Lo he metido dentro de personajes. Gracias.
