### ISSUE TITLE
Actualizar info en la wiki sobre lista de acciones predefinidas y sus sinónimos

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#14]
En https://github.com/Baltasarq/fi-js/wiki/Lista-de-acciones#lista-de-acciones hay por lo menos una que habría que actualizar, drop soporta también "lanzar", "lanza", "lanzo". Igual es la única que no está actualizada, no he mirado en detalle, pero estuve a punto de crear la acción "lanzar" hasta que vi que funcionaba con lo que ya había puesto para "dejar".

**Comment by Baltasarq** [comment]
He arreglado la lista de sinónimos en cuanto a _Drop_.

**Comment by paravaariar** [comment]
Veo que todavía hay otros casos, por ejemplo la acción "start"

**Comment by Baltasarq** [comment]
Actualizada la lista y ordenada.

**Comment by paravaariar** [comment]
Creo falta beber en "have"

**Comment by Baltasarq** [comment]
Arreglado.
