### ISSUE TITLE
Logotipo para fi-js

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#17]
Es una tontería, pero un logo puede hacer el framework más reconocible por la gente :)

**Comment by Baltasarq** [comment]
Puede ser, pero yo no soy muy diestro con los temas gráficos. Si alguien se ofrece, genial.

**Comment by paravaariar** [comment]
Tienes algún objeto, personaje, o algo que te sugiera el framework? No lo sé, un arquero, un arco, una flecha, otra cosa?
