### ISSUE TITLE
Texto que solo se visualizará una vez: Parece que solo permite unas llaves por descripción

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#18]
Cuando se usa el modificador ^{ } descrito en https://github.com/Baltasarq/fi-js/wiki/Loc#modificaciones-en-los-textos
 parece que solo funciona si la descripción tiene unas llaves.
Si ponemos por ejemplo:
^{Mi texto solo una vez.} Más texto. ^{Otra parte del texto solo una vez.}
La primera vez que entramos pone: Mi texto solo una vez. Más texto. ^{Otra parte del texto solo una vez.}
La segunda vez que ponemos "mirar", aparece Más texto. ^{Otra parte del texto solo una vez.}

**Comment by Baltasarq** [comment]
Sí, así es. El texto que solo va a aparecer una vez puede aparecer al principio, al final, o incluso (raro es) en el medio, pero solo un texto. No veo necesario que puedan aparecer varias instancias. ¿Debe concatenarse todo ese texto? ¿Es texto que es necesario "controlar", por cada uno de ellos, para que solo aparezca una vez? De verdad que me parece una complicación que no merece la pena.
