### ISSUE TITLE
Booleano de configuración para decir si quieres que aparezca la lista de objetos en las localizaciones o no

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#19]
Por defecto, al final del texto de una localización aparece la lista sintética de objetos que hay presentes.
Creo que no hay alguna forma de desactivar esto. Lo quité añadiendo `if (loc != player) { return "" };` después de está línea
https://github.com/Baltasarq/fi-js/blob/453f578da21f8231b8e0916cf01b00cdbfdd7ae3/lib/fi.js#L2199
pero estaría bien que fuese una especie de parámetro de configuración a nivel global que por defecto esté activado pero que se pueda cambiar.

**Comment by Baltasarq** [comment]
Mmmm... ya veo. Supongo que para lo que quieres tú te vale, pero en realidad `ctrl.list()` está pensada para ser usable al margen de la desc de las localidades.

Creo que se podría hacer pero quedaría mucho más limpio en `ctrl.updateDesc()`, en la [línea en la que de hecho se pide listar los objetos](https://github.com/Baltasarq/fi-js/blob/453f578da21f8231b8e0916cf01b00cdbfdd7ae3/lib/fi.js#L1757). También aquí (un pelín más abajo), se podría introducir tu siguiente petición.

**Comment by Baltasarq** [comment]
Esto está ya implementado, e incluído en la Wiki:
[Wiki para la referencia de localidades](https://github.com/Baltasarq/fi-js/wiki/Referencia-para-localidades).
