### ISSUE TITLE
Sale del juego al poner encender algo que no existe

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#21]
Por ejemplo, en vampiro https://baltasarq.github.io/fi-js/lib/ ponemos "encender antorcha" sale del juego a una página 404. La solución creo que es en vergs.js, en startAction.doIt = function(s) {, añadir un if ( objDest != null ) { justo después del primer else. Parece que así está hecho para las otras acciones.

**Comment by Baltasarq** [comment]
¡Arreglado!
Gracias por el informe tan detallado y por tu interés en fi.js.

[Commit "[Fixes crash when no object is found to be started](https://github.com/Baltasarq/fi-js/commit/dd7c9a825d4c0234262f654dd50414e3504ef0e2)"](https://github.com/Baltasarq/fi-js/commit/dd7c9a825d4c0234262f654dd50414e3504ef0e2).
