### ISSUE TITLE
Bug al llamar a updateDesc sin los dos parámetros

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#5]
Este bug está relacionado con #3 pero por lo menos no era tan bloqueante.
Si llamamos a updateDesc con un solo argumento, por ejemplo un preLook() como dice la Wiki resulta que loc tiene el valor de un String... y ahí empiezan los problemas que hace que luego falle todo. El chequeo de argumentos que hay ahora no lo soluciona.
```
       function updateDesc(loc, desc)
        {
            ...
            if ( arguments.length < 1
              || loc == null )
            {
                loc = ctrl.places.getCurrentLoc();
            }

            if ( arguments.length < 2
              || desc == null )
            {
                desc = loc.desc;
            }
```

**Comment by Baltasarq** [comment]
No se debería llamar a updateDesc() con solo un texto, eso es un error de la wiki, no del código. De hecho, me estoy temiendo que el texto que citas de la wiki explica cómo funciona, no cómo se debe usar.

**Comment by paravaariar** [comment]
En la wiki está en Miscelánea, en el tercer punto. El trozo de código pone `ctrl.lugares.updateDesc( ctrl.lugares.getCurrentLoc().preLook() );` y así falla.

**Comment by Baltasarq** [comment]
Corregido. ¡Muchas gracias!
