### ISSUE TITLE
Intro text en los mensajes no está documentado en la Wiki

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#6]
No estoy 100% seguro pero creo que la Wiki no menciona lo que se puede hacer gracias al método buildDescOfEntity
````
* Takes a description and removes or prepends
     * the intro text, marked with ^{ and }
     *  i.e. "^{This only appears once. }This is the regular desc."
     * ```

**Comment by Baltasarq** [comment]
Correcto. Actualizado en la wiki, sección "localidades".

**Comment by paravaariar** [comment]
Me pregunto si esta información no estaría mejor en la anterior de Mensajes que en Localidades: https://github.com/Baltasarq/fi-js/wiki/Msg    En localidades también está bien pero como es algo más en plan global...

En el ejemplo que has puesto `ctrl.creaObj( "mesa", [], "^{Esta mesa te trae funestos recuerdos. } Su superficie está pulida como un espejo.}")` no sobra el corchete después de `espejo.`?

**Comment by Baltasarq** [comment]
El tema de los mensajes no es muy genérico, se trata de un objeto dedicado a "generar" mensajes en secuencia o aleatorios. Por eso no me gusta esa sección.

En cuanto a la llave, sí, ya está solucionado. ¡Gracias!

**Comment by paravaariar** [comment]
Perfecto. Gracias a ti. Por cierto, en discord he puesto un pantallazo de lo que estoy haciendo y algún comentario sobre fi-js
