### ISSUE TITLE
Comando del jugador para reiniciar la partida

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#8]
Parece que no es posible para el jugador de reiniciar, sin que tenga que dar a actualizar el navegador, no?

**Comment by Baltasarq** [comment]
Sí, es correcto. El reinicio se haría actualizando la página. No me pareció necesario hacer nada más.

Pensando en las diferentes posibilidades, es un tema complicado. Habría que recorrer todos los objetos de nuevo colocándolos en su estado inicial. Aunque ahora hay un método ini(), no siempre fue así. Además, puede que el estado inicial dependa de cómo fue creado en sí.

En la práctica, creo que no es factible.

**Comment by Baltasarq** [comment]
Oh sí, eso sin problema: `window.location.reload();'.
De hecho, en la parte final de mis juegos es lo que hago para que el usuario no tenga que refrescar manualmente.

**Comment by paravaariar** [comment]
He añadido esto en mi juego. Supongo que sería a evaluar si un comando más o menos con este comportamiento no sería interesante a formar parte del propio motor...

```
const restartAction = actions.crea(
    "restart",
    [ "reiniciar"]
);

restartAction.doIt = function(s) {
    const response = confirm("¿Seguro que quieres reiniciar? Se perderá la partida actual.");
    if (response) {
        window.location.reload();
    } else {
        return "Partida no reiniciada.";
    }
};
```

**Comment by Baltasarq** [comment]
Hecho.
