### ISSUE TITLE
Bug en la doc con respecto a buscar acciones?

### ISSUE THREAD

**Issue by paravaariar** [Baltasarq/fi-js#9]
En https://github.com/Baltasarq/fi-js/wiki/Creando-acciones-nuevas#buscando-una-acci%C3%B3n pone el código siguiente un par de veces
`const examineAction = actions.getAction( "examine" );`
pero cuando lo uso me da error:
"caught SyntaxError: Identifier 'examineAction' has already been declared"
creo que abría que borrar el const, pero si borro el const me pone "caught TypeError: Assignment to constant variable."...

**Comment by Baltasarq** [comment]
Mmm... ya veo. Se trata de que `verbs.js` ya crea una *examineAction*, y efectivamente, al utilizar **const**, no se puede redefinir. Creo que es mejor cambiarle el nombre, de hecho.

**Comment by Baltasarq** [comment]
Hecho.
